CREATE DATABASE IF NOT EXISTS bagavathy_portfolio CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bagavathy_portfolio;

CREATE TABLE IF NOT EXISTS projects (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(180) NOT NULL, slug VARCHAR(180) NOT NULL UNIQUE,
 short_description VARCHAR(500) NOT NULL, description TEXT NOT NULL,
 category VARCHAR(80) NOT NULL, technologies TEXT NOT NULL,
 image_url VARCHAR(500) NULL, github_url VARCHAR(500) NULL, demo_url VARCHAR(500) NULL,
 featured BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_projects_category(category)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS experiences (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, organization VARCHAR(180) NULL, role VARCHAR(180) NOT NULL,
 type VARCHAR(80) NULL, start_date VARCHAR(30) NULL, end_date VARCHAR(30) NULL,
 description TEXT NULL, certificate_url VARCHAR(500) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS certifications (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(220) NOT NULL, issuer VARCHAR(180) NOT NULL,
 issue_date VARCHAR(30) NULL, credential_url VARCHAR(500) NULL, certificate_image VARCHAR(500) NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS contact_messages (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL, email VARCHAR(160) NOT NULL,
 subject VARCHAR(160) NOT NULL, message TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_contact_created(created_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS site_settings (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, setting_key VARCHAR(100) NOT NULL UNIQUE,
 setting_value TEXT NULL
) ENGINE=InnoDB;